import React from 'react';
import { ArrowLeft } from 'lucide-react';
import { Button } from '../ui/button';

export function TosPage({ onBack }: { onBack: () => void }) {
  return (
    <div className="min-h-screen bg-background flex flex-col items-center py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl w-full space-y-8">
        <Button variant="ghost" onClick={onBack} className="mb-4">
          <ArrowLeft className="mr-2 h-4 w-4" /> Back to Home
        </Button>
        <h1 className="text-4xl font-bold tracking-tight">Terms of Service</h1>
        <div className="prose dark:prose-invert max-w-none text-muted-foreground space-y-6">
          <p className="text-lg">
            By using Cramly, you agree to the following terms:
          </p>
          <div>
            <h3 className="text-xl font-semibold text-foreground">Usage Limits</h3>
            <p>Free accounts are provided with a specific quota of cheatsheet generations per month to ensure fair usage for everyone.</p>
          </div>
          <div>
            <h3 className="text-xl font-semibold text-foreground">Appropriate Content</h3>
            <p>Users must not use the tool to generate content that is illegal, harmful, or violates any policies.</p>
          </div>
          <div>
            <h3 className="text-xl font-semibold text-foreground">Service Availability</h3>
            <p>While we strive for 100% uptime, the AI generation depends on external providers and may occasionally experience delays.</p>
          </div>
          <div>
            <h3 className="text-xl font-semibold text-foreground">Accuracy of Information</h3>
            <p>The cheatsheets are generated by AI. While we aim for high accuracy, users should verify critical information before using it for formal exams.</p>
          </div>
        </div>
      </div>
    </div>
  );
}
